### ISSUE TITLE
Virustotal 8/68 detections

### ISSUE THREAD

**Issue by ImiAtEm** [OCSInventory-NG/Packager-for-Windows#13]
![image](https://user-images.githubusercontent.com/73164664/124752702-7932f280-df28-11eb-839d-0f24f2a55d10.png)

May I request that you sign the .exe?

**Comment by gillesdubois** [comment]
Hi,

If you scanned the resulting file of the windows packager, it can be marked as mallicious because the behavior of the packager is to reinject parameters inside the setup.

We can sign the file but that wouldn't change the result IMO. 
You can try to scan the setup file of the agent we provide, this one should clear of any detection.

Regards,
Gilles.

**Comment by ImiAtEm** [comment]
Hi Gilles,

Woah, fast response, respect ! ^^

This is the virustotal result for "OCS-Windows-Agent-Setup-x64.exe", which is the Windows Agent 2.8.0.0 (64 bits) in the download email.
![image](https://user-images.githubusercontent.com/73164664/124756831-345d8a80-df2d-11eb-8810-2bf560f90bf2.png)

It looks much better for sure, signing would also help with windows smartscreen though.


BR,
Imre

**Comment by gillesdubois** [comment]
Ok thanks for your input, we'll try to sign the new release coming up :) 

Regards,
Gilles.

**Comment by ImiAtEm** [comment]
Awesome, thanks ! 
Great software btw, thanks for your contributions! ^-^

BR,
Imre
